import FilterContextProvide from "../actions/context/filterContext";
import HomeNav from "./homeComponents/HomeNav";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function layout({ children }) {
    return (
        <div className="flex flex-col w-full h-dvh">
            <FilterContextProvide>
            <HomeNav />
            {children}
            </FilterContextProvide>
        </div>
    );
}
