import { Inter } from 'next/font/google'
import { GeistSans } from 'geist/font/sans';
import './globals.css'
import { Toaster } from "@/components/ui/sonner"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='dark'>
      <body className={`${GeistSans.className} flex flex-col w-full h-dvh`}>
        {children}
        <Toaster expand visibleToasts={1} position="top-center"/>
        </body>
    </html>
  )
}
